// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihileabinwmxfxxcmfhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloaWxlYWJpbndteGZ4eGNtZmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1MDYxMDYsImV4cCI6MjA1MDA4MjEwNn0.zOqPea3YhjVMBjxhNWHMLmR20J6l7FVYivSBFJThgcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);